### ISSUE TITLE
console-commando incompatible with node version 4.4.7

### ISSUE THREAD

**Issue by thinkrapido** [lucascaro/console-commando#2]
```
...\node_modules\console-commando\lib\commando.js:171
    run(rootCommand = this) {
                    ^

SyntaxError: Unexpected token =
```

should be 

```
run(rootCommand) {
   rootCommand = rootCommand || this;
```

You should consider to make your project compatible to older versions of node or give a warning in the Readme.

**Comment by lucascaro** [comment]
thanks for the feedback @thinkrapido 
version 1.x is compatible down to node 0.12 and has feature parity with 2.x, you might want to give it a try.

I am planning to add babel back and add support for older node versions in 2.x soon.

**Comment by lucascaro** [comment]
@thinkrapido added back support for es5 in 3.0.0+
Note that due to a small breaking change, I incremented the major version number.
Since I added compatibility to use CommonJS modules and fixed typescript definitions, projects using require will need to do

```js
var Commando = require('console-commando').default
```
